### ISSUE TITLE
Cannot initialize new instance of inotify, Errno=Too many open files (EMFILE)

### ISSUE THREAD

**Issue by vallsv** [moddevices/mod-sdk#15]
Hi,

Here is what i often reach without doing much things:
```
Cannot initialize new instance of inotify, Errno=Too many open files (EMFILE)
```

I mitigate the problem this way:
```
 class BundleMonitorWebsocket(websocket.WebSocketHandler):
     def open(self):
-        self.monitor = BundleMonitor(self.notify)
+        try:
+            self.monitor = BundleMonitor(self.notify)
+        except Exception as e:
+            print(e)
+            self.monitor = None

     def on_message(self, bundle):
         self.monitor.monitor(bundle)

     def on_close(self):
-        self.monitor.clear()
+        if self.monitor:
+            self.monitor.clear()
```
But i guess things are broke anyway.

**Comment by vallsv** [comment]
Here is the traceback
```
Traceback (most recent call last):
  File "/home/ordinateur/Software/miniconda3/envs/moddevices/lib/python3.5/site-packages/tornado/websocket.py", line 546, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/ordinateur/Software/miniconda3/envs/moddevices/lib/python3.5/site-packages/modsdk/webserver.py", line 724, in open
    self.monitor = BundleMonitor(self.notify)
  File "/home/ordinateur/Software/miniconda3/envs/moddevices/lib/python3.5/site-packages/modsdk/bundlemonitor.py", line 31, in __init__
    self.wm = pyinotify.WatchManager()
  File "/home/ordinateur/Software/miniconda3/envs/moddevices/lib/python3.5/site-packages/pyinotify.py", line 1764, in __init__
    raise OSError(err % self._inotify_wrapper.str_errno())
OSError: Cannot initialize new instance of inotify, Errno=Too many open files (EMFILE)
```

**Comment by vallsv** [comment]
I think it was because `lilv` was not able to load my plugin.
